# Generated by Django 2.2 on 2021-05-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlshort',
            name='slug',
        ),
        migrations.AlterField(
            model_name='urlshort',
            name='short_url',
            field=models.SlugField(default='xxxx', unique=True),
        ),
        migrations.AlterField(
            model_name='urlshort',
            name='url',
            field=models.TextField(default='http://'),
        ),
    ]
