# Generated by Django 2.2 on 2021-05-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20210505_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlshort',
            name='short_url',
            field=models.CharField(default='xxxx', max_length=25),
        ),
    ]
